### ISSUE TITLE
Issue with precision in string formatting with float numbers

### ISSUE THREAD

**Issue by VVionnet** [Chrismarsh/mesher#10]
mesher.py uses the following command: 

`exec_str = 'gdalwarp %s %s -overwrite -dstnodata -9999 -t_srs "%s" -te %f %f %f %f  -tr %f %f -r '`

where `%f` can potentially lead to a limited precision for raster extent and resolution. This matters for very high resolution lat/lon grid. Would it be possible to correct it? 

e.g.,
raster has width 0.0001796630568239043 deg which is changed into 0.000018 deg

**Comment by Chrismarsh** [comment]
I think the best approach is to specify a fixed precision with the %f specifier?

**Comment by VVionnet** [comment]
Yes totally. Maybe you can set a default values such as '%.5f' and the user can adjust that in the config file.

**Comment by Chrismarsh** [comment]
Is there any harm in just using 30digits all the time? It should be fine with that.

**Comment by VVionnet** [comment]
Yes. I think it would a good option.

**Comment by Chrismarsh** [comment]
I think changing this to be strings is the best solution
i=0.0001796630568239043
In [2]:   '%s' % i
Out[2]: '0.000179663056824'
