### ISSUE TITLE
cannot handle projection name with space

### ISSUE THREAD

**Issue by wspruce** [Chrismarsh/mesher#16]
Hello, 
 `GetProjection()` returns a projection name with space in it which causes the `ogr2ogr` commend to broke.
This occurs to me when trying the ` stream_dem ` example which has the projection name of "NAD83 / UTM zone 8N"

write
```
use_input_prj = False
wkt_out = Projection name with spaces replaced by _
```
into the parameter `.py` file is ok for now

**Comment by Chrismarsh** [comment]
Interesting, thanks for the report. I'll look into this.
