### ISSUE TITLE
Step 2, 3?

### ISSUE THREAD

**Issue by r-barnes** [Chrismarsh/mesher#2]
On [this line](https://github.com/r-barnes/mesher/blob/89f81068cd0c936768a84bf8f1310d47e7a226c0/mesher.py#L305), I see "Step 1".

Where are Steps 2 and 3?

Additional comments explaining what each part of the code is doing would be helpful.

Splitting up `main()` into subfunctions which capture the separate steps is another potentially-desirable option.

**Comment by Chrismarsh** [comment]
More comments were added for clarity
