### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by r-barnes** [Chrismarsh/mesher#3]
If possible, please upgrade your script to Python3. This should be fairly painless using the [automated scripts](https://docs.python.org/2/library/2to3.html), it future-proofs your code, and it my confer some performance benefits.

Python2 will no longer be supported past 2020 ([countdown](https://pythonclock.org/)): unless there are compelling reasons not to, let's embrace the inevitable future.

**Comment by Chrismarsh** [comment]
>unless there are compelling reasons not to, let's embrace the inevitable future.

I don't disagree. Using Python 2 was entirely a result of the workstations I use having Python2 default. I do not believe there is anything that should break under Python 3.

**Comment by r-barnes** [comment]
Most (government/university) supercomputers allow you to include Python 3 using the `module` command; otherwise, Anaconda's got me up and running with a home-directory installation a few times when the default system packages didn't work.

**Comment by Chrismarsh** [comment]
GDAL --with-python via Homebrew on macOS does not appear to support python3. If it does, I'm doing something wrong.  Todo: investigate further.

**Comment by Chrismarsh** [comment]
py2to3 has been run and has prelimiary python3 support. Homebrew issue remains.

**Comment by Chrismarsh** [comment]
Python 3 is fully supported
