### ISSUE TITLE
What is meant by "constrained"?

### ISSUE THREAD

**Issue by r-barnes** [Chrismarsh/mesher#6]
In your readme file you state the following:

> An example of this is shown below, where the triangulation (black lines) are constrained to topography (not shown) and vegetation landclasses (coloured squares).

Is it possible to add an expanded explanation of what is meant by constraints and what the colors representing vegetation land classes mean? At present, if I squint, I can see that the size of the triangles varies between the regions, I think a little more explanation would make it more clear to a reader what exactly they should be looking for in this example image in order to better appreciate what your algorithm does.

**Comment by Chrismarsh** [comment]
For clarity it should be 'conditioned to' or 'refined to' (or a similar term -- I will need to think on the best term to use for the README. Always best to reduce jargon upfront). Constrained triangulations generally consider any define region a triangle may not intersect. I agree for clarity that should be changed. Re: your other point, that can be added to make it more clear.
