### ISSUE TITLE
LICENSING

### ISSUE THREAD

**Issue by r-barnes** [Chrismarsh/mesher#8]
It's great that you've decided to provide a license with your code! This reduces ambiguity about how the code can be used and, hopefully, will increase its usage.

If you name the file correctly, Github will [detect it](https://github.com/blog/2252-license-now-displayed-on-repository-overview). More help [here](https://help.github.com/articles/licensing-a-repository/).

**Comment by Chrismarsh** [comment]
Didn't realize it had not been automatically detected. Should be good now in 6714e111

**Comment by r-barnes** [comment]
Yup, looks good from my end.
