### ISSUE TITLE
suggestion for usage

### ISSUE THREAD

**Issue by jfburkhart** [Chrismarsh/mesher#9]
I suggest a workflow with the following (similar) environment variables:

```
#mesher
export MESHER_EXE=/dev/cust_python/mesher-dist/bin/mesher
export MESHER_HOME=/dev/cust_python/mesher-dist
export PATH=${MESHER_HOME}:$PATH
```
And adding the following lines to `mesher.py`:

```
1d0
< #!/usr/bin/env python
29,35d27
< import os
<
< try:
<     MESHER_EXE = os.environ['MESHER_EXE']
< except KeyError as E:
<     print('{0} not found in environment'.format(E))
<     MESHER_EXE = os.path.join('bin', 'mesher')
```
This enables a workflow of:

```
mesher.py config.py
```
Which may be simpler than referring to `../../mesher.py` or similar from wherever you are on your system.

**Comment by Chrismarsh** [comment]
@jfburkhart Thanks for the feedback. It's a good idea. I'll add support for this.
